const FoodTypes = {
    TOP_CATEGORY_REQUEST : 'TOP_CATEGORY_REQUEST',
    TOP_CATEGORY_SUCCESS : 'TOP_CATEGORY_SUCCESS',
    TOP_CATEGORY_FAIL : 'TOP_CATEGORY_FAIL',
    TOP_CATEGORY_RESET : 'TOP_CATEGORY_RESET',


    POPULAR_FOOD_REQUEST : 'POPULAR_FOOD_REQUEST',
    POPULAR_FOOD_SUCCESS : 'POPULAR_FOOD_SECCUESS',
    POPULAR_FOOD_FAIL: 'POPULAR_FOOD__FAIL',
    POPULAR_FOOD_RESET: 'POPULAR_FOOD_RESET',


    FOOD_DETAILS_REQUEST : 'FOOD_DETAILS_REQUEST',
    FOOD_DETAILS_SUCCESS : 'FOOD_DETAILS_SECCUESS',
    FOOD_DETAILS_FAIL: 'FOOD_DETAILS_FAIL',
    FOOD_DETAILS_RESET: 'FOOD_DETAILS_RESET'
}

export default FoodTypes;